#!/bin/bash
"""
Jira Daily Finance Summary Script
Auto-create daily Jira issues dengan finance tracker summary
Trigger via cron job (daily)
"""

#!/bin/bash

# Configuration
JIRA_DOMAIN="your-domain.atlassian.net"
JIRA_EMAIL="your-email@company.com"
JIRA_TOKEN="your_api_token"
JIRA_PROJECT="FIN"

FINANCE_DIR="/home/ubuntu/finance-tracker"
PYTHON="/usr/bin/python3"

# Get current balance & stats
echo "=== Fetching Finance Data ===" >&2

BALANCE=$(curl -s http://127.0.0.1:5000/api/balance 2>/dev/null | python3 -c "import sys, json; data=json.load(sys.stdin); print(data['data']['balance'])")
INCOME=$(curl -s http://127.0.0.1:5000/api/balance 2>/dev/null | python3 -c "import sys, json; data=json.load(sys.stdin); print(data['data']['income'])")
EXPENSE=$(curl -s http://127.0.0.1:5000/api/balance 2>/dev/null | python3 -c "import sys, json; data=json.load(sys.stdin); print(data['data']['expense'])")

# Get transaction count
TX_COUNT=$(curl -s http://127.0.0.1:5000/api/transactions 2>/dev/null | python3 -c "import sys, json; data=json.load(sys.stdin); print(len(data.get('data', {}).get('transactions', [])))" || echo "0")

# Get debt summary
DEBT_DATA=$(curl -s http://127.0.0.1:5000/api/debts 2>/dev/null | python3 -c "import sys, json; data=json.load(sys.stdin); debts=data.get('data', {}).get('debts', []); print(f'{len(debts)}|{sum([d[\"amount\"] for d in debts])}')" || echo "0|0")

DEBT_COUNT=$(echo $DEBT_DATA | cut -d'|' -f1)
DEBT_TOTAL=$(echo $DEBT_DATA | cut -d'|' -f2)

TODAY=$(date +%Y-%m-%d)
TIMESTAMP=$(date +%Y-%m-%d\ %H:%M:%S)

# Format numbers
format_rupiah() {
    printf "%'d" $1 | sed 's/,/./g'
}

BALANCE_FMT=$(format_rupiah $BALANCE)
INCOME_FMT=$(format_rupiah $INCOME)
EXPENSE_FMT=$(format_rupiah $EXPENSE)
DEBT_TOTAL_FMT=$(format_rupiah $DEBT_TOTAL)

# Build Jira issue
SUMMARY="Daily Finance Summary - $TODAY"

DESCRIPTION="*Finance Tracker Daily Report*

*Metrics:*
• Balance: Rp $BALANCE_FMT
• Income: Rp $INCOME_FMT
• Expense: Rp $EXPENSE_FMT
• Transactions: $TX_COUNT
• Debts: $DEBT_COUNT (Total: Rp $DEBT_TOTAL_FMT)

*Generated:* $TIMESTAMP

[Auto-generated by Finance Tracker Cron Job]"

echo "=== Creating Jira Issue ===" >&2

# Create issue via Python script
$PYTHON $FINANCE_DIR/jira_client.py create \
    "$JIRA_DOMAIN" \
    "$JIRA_EMAIL" \
    "$JIRA_TOKEN" \
    "$JIRA_PROJECT" \
    "$SUMMARY" \
    "$DESCRIPTION"

echo "✅ Daily summary created" >&2
